### ISSUE TITLE
Unity version 4.x

### ISSUE THREAD

**Issue by ac931274** [dchaib/Glimpse.Unity#2]
Are you planning on releasing a version for version 4 of Unity please?

**Comment by dchaib** [comment]
To be honest, I haven't planned anything. But if it is useful to somebody, I will have a look. Unfortunately, I cannot do it in the coming weeks. In the meantime, if you are interested, feel free to submit a pull request! :-)

**Comment by dchaib** [comment]
I'm sorry it has taken so long, but a new version with support for Unity 4.0.1 has been uploaded to NuGet. Let me know how it works for you!
